### ISSUE TITLE
Migrate to Hugo

### ISSUE THREAD

**Issue by nullcubee** [LearnerCouncil/LCSite#15]
Considering this theme:
- [Paige | Hugo Themes](https://themes.gohugo.io/themes/paige/) 

Would solve #6 and #8

### Todo:
- [ ] Remove 11ty
- [ ] Add Hugo
- [ ] Add Hugo Theme
- [ ] Migrate Azure Github Action
- [ ] Configure Hugo
- [ ] Edit website content (if needed)
